# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\tomre\PycharmProjects\Architecture\ui\components\page_person.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_page_bmi_calculation(object):
    def setupUi(self, page_bmi_calculation):
        page_bmi_calculation.setObjectName("page_bmi_calculation")
        page_bmi_calculation.resize(799, 686)
        self.verticalLayout = QtWidgets.QVBoxLayout(page_bmi_calculation)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea = QtWidgets.QScrollArea(page_bmi_calculation)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 779, 666))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.content = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.content.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.content.setFrameShadow(QtWidgets.QFrame.Raised)
        self.content.setObjectName("content")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.content)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_title = QtWidgets.QLabel(self.content)
        self.label_title.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_title.setFont(font)
        self.label_title.setAlignment(QtCore.Qt.AlignCenter)
        self.label_title.setObjectName("label_title")
        self.verticalLayout_2.addWidget(self.label_title)
        self.frame_persons = QtWidgets.QFrame(self.content)
        self.frame_persons.setStyleSheet("background-color: rgb(255, 251, 220);")
        self.frame_persons.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_persons.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_persons.setObjectName("frame_persons")
        self.layout_persons = QtWidgets.QVBoxLayout(self.frame_persons)
        self.layout_persons.setContentsMargins(1, 1, 1, 1)
        self.layout_persons.setSpacing(1)
        self.layout_persons.setObjectName("layout_persons")
        self.verticalLayout_2.addWidget(self.frame_persons)
        self.frame_button = QtWidgets.QFrame(self.content)
        self.frame_button.setMinimumSize(QtCore.QSize(0, 50))
        self.frame_button.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_button.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_button.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_button.setObjectName("frame_button")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_button)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_add_person = QtWidgets.QPushButton(self.frame_button)
        self.btn_add_person.setObjectName("btn_add_person")
        self.horizontalLayout.addWidget(self.btn_add_person)
        self.btn_calculate_all = QtWidgets.QPushButton(self.frame_button)
        self.btn_calculate_all.setObjectName("btn_calculate_all")
        self.horizontalLayout.addWidget(self.btn_calculate_all)
        self.verticalLayout_2.addWidget(self.frame_button)
        self.frame_visual = QtWidgets.QFrame(self.content)
        self.frame_visual.setStyleSheet("background-color: rgb(219, 216, 255);")
        self.frame_visual.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_visual.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_visual.setObjectName("frame_visual")
        self.layout_visual = QtWidgets.QHBoxLayout(self.frame_visual)
        self.layout_visual.setObjectName("layout_visual")
        self.verticalLayout_2.addWidget(self.frame_visual)
        self.verticalLayout_3.addWidget(self.content)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)

        self.retranslateUi(page_bmi_calculation)
        QtCore.QMetaObject.connectSlotsByName(page_bmi_calculation)

    def retranslateUi(self, page_bmi_calculation):
        _translate = QtCore.QCoreApplication.translate
        page_bmi_calculation.setWindowTitle(_translate("page_bmi_calculation", "Form"))
        self.label_title.setText(_translate("page_bmi_calculation", "BMI Calculator"))
        self.btn_add_person.setText(_translate("page_bmi_calculation", "add Person"))
        self.btn_calculate_all.setText(_translate("page_bmi_calculation", "calculate all"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    page_bmi_calculation = QtWidgets.QWidget()
    ui = Ui_page_bmi_calculation()
    ui.setupUi(page_bmi_calculation)
    page_bmi_calculation.show()
    sys.exit(app.exec_())
