# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\tomre\PycharmProjects\Architecture\ui\Components\toolbar\sidemenu.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt, QPropertyAnimation


class SidemenuView(object):
    def __init__(self, layout):
        self.widget_side_menu = QtWidgets.QWidget()
        layout.addWidget(self.widget_side_menu)
        self.setupUi(self.widget_side_menu)

    def setupUi(self, widget_side_menu):
        widget_side_menu.setObjectName("widget_side_menu")
        widget_side_menu.resize(94, 791)
        self.horizontalLayout = QtWidgets.QHBoxLayout(widget_side_menu)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_side_menu = QtWidgets.QFrame(widget_side_menu)
        self.frame_side_menu.setMinimumSize(QtCore.QSize(70, 0))
        self.frame_side_menu.setMaximumSize(QtCore.QSize(70, 16777215))
        self.frame_side_menu.setAutoFillBackground(False)
        self.frame_side_menu.setStyleSheet("background-color: rgb(80, 74, 64);")
        self.frame_side_menu.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_side_menu.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_side_menu.setLineWidth(1)
        self.frame_side_menu.setObjectName("frame_side_menu")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_side_menu)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout.addWidget(self.frame_side_menu)

        self.retranslateUi(widget_side_menu)
        QtCore.QMetaObject.connectSlotsByName(widget_side_menu)

    def retranslateUi(self, widget_side_menu):
        _translate = QtCore.QCoreApplication.translate
        widget_side_menu.setWindowTitle(_translate("widget_side_menu", "Form"))

    def extend(self, button_names):
        self.change_width(200)
        #ToDo enable fields with ButtonNames and show them next to the Button in an extra function

    def minimize(self):
        self.change_width(70)
        #ToDo hide visibility of ButtonNames in an extra function

    def change_width(self, end_width):
        width = self.frame_side_menu.width()
        self.animation = QPropertyAnimation(self.frame_side_menu, b"minimumWidth")
        self.animation.setDuration(300)
        self.animation.setStartValue(width)
        self.animation.setEndValue(end_width)
        self.animation.setEasingCurve(QtCore.QEasingCurve.InOutQuart)
        self.animation.start()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    widget_side_menu = QtWidgets.QWidget()
    ui = SidemenuView()
    ui.setupUi(widget_side_menu)
    widget_side_menu.show()
    sys.exit(app.exec_())
